/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Michael;

import Alex.HealthTracker;
import Tien.HabitBuilder;
import healthylife.HealthGUI;
/**
 *
 * @author mikey
 */
public class WellnessEducation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WellnessEducation.class.getName());

    /**
     * Creates new form WellnessEducation
     */
    public WellnessEducation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tipsTA = new javax.swing.JTextArea();
        WellnessEducationLBL = new javax.swing.JLabel();
        mainMenuBTN = new javax.swing.JButton();
        HabitBuilderBTN = new javax.swing.JButton();
        HealthTrackerBTN = new javax.swing.JButton();
        EXITbtn = new javax.swing.JButton();
        healthtipsLBL = new javax.swing.JLabel();
        showtipBTN = new javax.swing.JButton();
        optionaRB = new javax.swing.JRadioButton();
        optionbRB = new javax.swing.JRadioButton();
        optioncRB = new javax.swing.JRadioButton();
        questionLBL = new javax.swing.JLabel();
        optiondRB = new javax.swing.JRadioButton();
        quizBTN = new javax.swing.JButton();
        nextBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipsTA.setEditable(false);
        tipsTA.setColumns(20);
        tipsTA.setRows(5);
        jScrollPane1.setViewportView(tipsTA);

        WellnessEducationLBL.setText("Wellness Education");

        mainMenuBTN.setText("Main Menu");
        mainMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBTNActionPerformed(evt);
            }
        });

        HabitBuilderBTN.setText("Habit Builder");
        HabitBuilderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitBuilderBTNActionPerformed(evt);
            }
        });

        HealthTrackerBTN.setText("Health Tracker");
        HealthTrackerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthTrackerBTNActionPerformed(evt);
            }
        });

        EXITbtn.setText("Exit");
        EXITbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITbtnActionPerformed(evt);
            }
        });

        healthtipsLBL.setText("Health Tips");

        showtipBTN.setText("Show Tip");

        optionaRB.setText("Option A");

        optionbRB.setText("Option B");

        optioncRB.setText("Option C");

        questionLBL.setText("Click start quiz to generate a question");

        optiondRB.setText("Option D");

        quizBTN.setText("Start Quiz");

        nextBTN.setText("Next");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quizBTN)
                        .addGap(18, 18, 18)
                        .addComponent(nextBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showtipBTN))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(HealthTrackerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(HabitBuilderBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(optionbRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(optioncRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(optiondRB, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(optionaRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(272, 272, 272)
                                        .addComponent(mainMenuBTN))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EXITbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(healthtipsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(questionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(WellnessEducationLBL)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WellnessEducationLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(healthtipsLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showtipBTN)
                        .addGap(30, 30, 30)
                        .addComponent(HabitBuilderBTN)
                        .addGap(31, 31, 31)
                        .addComponent(HealthTrackerBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quizBTN)
                            .addComponent(nextBTN))))
                .addGap(12, 12, 12)
                .addComponent(questionLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionaRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionbRB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuBTN))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(EXITbtn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(optioncRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optiondRB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HealthTrackerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthTrackerBTNActionPerformed
        // TODO add your handling code here:
         new HealthTracker().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_HealthTrackerBTNActionPerformed

    private void HabitBuilderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitBuilderBTNActionPerformed
        // TODO add your handling code here:
        new HabitBuilder().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_HabitBuilderBTNActionPerformed

    private void mainMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBTNActionPerformed
        // TODO add your handling code here:
        new HealthGUI().setVisible(true);
        this.setVisible(false);
        System.out.println("closed");
        this.dispose();
    }//GEN-LAST:event_mainMenuBTNActionPerformed

    private void EXITbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WellnessEducation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXITbtn;
    private javax.swing.JButton HabitBuilderBTN;
    private javax.swing.JButton HealthTrackerBTN;
    private javax.swing.JLabel WellnessEducationLBL;
    private javax.swing.JLabel healthtipsLBL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuBTN;
    private javax.swing.JButton nextBTN;
    private javax.swing.JRadioButton optionaRB;
    private javax.swing.JRadioButton optionbRB;
    private javax.swing.JRadioButton optioncRB;
    private javax.swing.JRadioButton optiondRB;
    private javax.swing.JLabel questionLBL;
    private javax.swing.JButton quizBTN;
    private javax.swing.JButton showtipBTN;
    private javax.swing.JTextArea tipsTA;
    // End of variables declaration//GEN-END:variables
}
